//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhật một dữ liệu để thực hiện hành động.
        /// </summary>
        internal static string Message_ChooseAtLeastOneData {
            get {
                return ResourceManager.GetString("Message_ChooseAtLeastOneData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ít nhất 1 sản phẩm!.
        /// </summary>
        internal static string Message_ChooseAtLeastOneProduct {
            get {
                return ResourceManager.GetString("Message_ChooseAtLeastOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string Message_Confirm {
            get {
                return ResourceManager.GetString("Message_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa.
        /// </summary>
        internal static string Message_DeleteData {
            get {
                return ResourceManager.GetString("Message_DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string Message_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Message_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu hiện đang còn dữ liệu.\n Nếu bạn xác nhận xoá, hệ thống sẽ xóa các dữ liệu chi tiết bên trong phiếu ! Xin vui lòng cân nhăc trước khi ấn nút xác nhận..
        /// </summary>
        internal static string Message_DeleteHaveData {
            get {
                return ResourceManager.GetString("Message_DeleteHaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý hiện tại hệ thống chỉ hỗ trợ xóa một cửa hàng nên vui lòng chọn đúng một cửa hàng để thực hiện thao tác !.
        /// </summary>
        internal static string Message_DeleteStore {
            get {
                return ResourceManager.GetString("Message_DeleteStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng  hiện đang còn dữ liệu và tài khoản hoạt động.\n Nếu bạn xác nhận xoá, hệ thống sẽ ngưng kích hoạt cửa hàng và các dữ liệu liên quan, thay vì xoá vĩnh viễn..
        /// </summary>
        internal static string Message_DeleteStoreHaveData {
            get {
                return ResourceManager.GetString("Message_DeleteStoreHaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên sản phẩm để có thể tìm kiếm dữ liệu trong kho.
        /// </summary>
        internal static string Message_EnterNameProductToFind {
            get {
                return ResourceManager.GetString("Message_EnterNameProductToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất Bại.
        /// </summary>
        internal static string Message_Fail {
            get {
                return ResourceManager.GetString("Message_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại Trung Quốc không hợp lệ. VD: +8613712345678 hoặc 13712345678.
        /// </summary>
        internal static string Message_InvalidChineseNumber {
            get {
                return ResourceManager.GetString("Message_InvalidChineseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại Nhật Bản không hợp lệ. VD: +819012345678 hoặc 09012345678.
        /// </summary>
        internal static string Message_InvalidJapaneseNumber {
            get {
                return ResourceManager.GetString("Message_InvalidJapaneseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại Hàn Quốc không hợp lệ. VD: +821012345678 hoặc 01012345678.
        /// </summary>
        internal static string Message_InvalidKoreanNumber {
            get {
                return ResourceManager.GetString("Message_InvalidKoreanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng không hợp lệ .
        /// </summary>
        internal static string Message_InvalidMonth {
            get {
                return ResourceManager.GetString("Message_InvalidMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ. Vui lòng kiểm tra lại định dạng!.
        /// </summary>
        internal static string Message_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("Message_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại Mỹ không hợp lệ. VD: +11234567890 hoặc 1234567890.
        /// </summary>
        internal static string Message_InvalidUSNumber {
            get {
                return ResourceManager.GetString("Message_InvalidUSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại Việt Nam không hợp lệ VD: +84912345678 hoặc 0912345678&quot;.
        /// </summary>
        internal static string Message_InvalidVietnameseNumber {
            get {
                return ResourceManager.GetString("Message_InvalidVietnameseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm không hợp lệ.
        /// </summary>
        internal static string Message_InvalidYear {
            get {
                return ResourceManager.GetString("Message_InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        internal static string Message_NoData {
            get {
                return ResourceManager.GetString("Message_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu trong khoảng thời gian này .
        /// </summary>
        internal static string Message_NotDataAtThisTime {
            get {
                return ResourceManager.GetString("Message_NotDataAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        internal static string Message_Notification {
            get {
                return ResourceManager.GetString("Message_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được để trống.
        /// </summary>
        internal static string Message_NotNull {
            get {
                return ResourceManager.GetString("Message_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm này không tồn tại trong kho hàng. Vui lòng nhập lại mã.
        /// </summary>
        internal static string Message_ProductNotInStock {
            get {
                return ResourceManager.GetString("Message_ProductNotInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng trong kho không đủ đế đáp ứng số lượng xuất của bạn vui lòng điều chỉnh lại số lượng!.
        /// </summary>
        internal static string Message_QuantityProductNotEnough {
            get {
                return ResourceManager.GetString("Message_QuantityProductNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng thực tế không thể lớn hơn số lượng hệ thống. Vui lòng kiểm lại!.
        /// </summary>
        internal static string Message_QuantityVariance {
            get {
                return ResourceManager.GetString("Message_QuantityVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công .
        /// </summary>
        internal static string Message_SavedSuccessfullLy {
            get {
                return ResourceManager.GetString("Message_SavedSuccessfullLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn quốc gia/vùng miền..
        /// </summary>
        internal static string Message_SelectNation {
            get {
                return ResourceManager.GetString("Message_SelectNation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn cửa hàng.
        /// </summary>
        internal static string Message_SelectStore {
            get {
                return ResourceManager.GetString("Message_SelectStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được chứa ký tự đặc biệt !.
        /// </summary>
        internal static string Message_SpecialCharacter {
            get {
                return ResourceManager.GetString("Message_SpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành Công.
        /// </summary>
        internal static string Message_Successfull {
            get {
                return ResourceManager.GetString("Message_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày phải nhỏ hơn đến ngày .
        /// </summary>
        internal static string Message_ToDayMoreThanFromDay {
            get {
                return ResourceManager.GetString("Message_ToDayMoreThanFromDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phải là số hợp lệ và không được để trống hoặc bằng 0.
        /// </summary>
        internal static string Message_ValidNumber {
            get {
                return ResourceManager.GetString("Message_ValidNumber", resourceCulture);
            }
        }
    }
}
